spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.payments.application.dto.WithdrawRequest
